Models/Dish.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestTaskPizza.Models
{
    public class Dish
    {
        //[Key]
        public int Id { get; set; }
        [Display(Name = "Название блюда")]
        [Required(ErrorMessage = "Пожалуйста, введите название блюда")]
        [MaxLength(128, ErrorMessage = "Максимальная длинна 128 символа")]
        public string Name { get; set; }

        [Display(Name = "Название рецепта")]
        [MaxLength(128, ErrorMessage = "Максимальная длинна 128 символа")]
        public string DishRecipeName { get; set; }
        [Display(Name = "Изображение")]
        public string ImagePath { get; set; }
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public float price { get; set; }        
        public int? GroupId { get; set; }
        [Display(Name = "Категория")]
        public virtual Group Group { get; set; }
        [Display(Name = "Рецепт")]

        public virtual ICollection<Recipe> Recipes { get; set; }

        public Dish()
        {
            //Список рецептов для комбо-набора
            Recipes = new List<Recipe>();
        }
    }
}

Controllers/DishSelectController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTaskPizza.Models.Repositories;
using TestTaskPizza.Models;

namespace TestTaskPizza.Controllers
{
    public class DishSelectController : Controller
    {
        UoW db;
        static DishSelect DishSelectView = new DishSelect();        
        public DishSelectController()
        {
            db = new UoW();
        }
        // GET: DishSelect
        public ActionResult Index()
        {
            return View();
        }
        // GET: Dishes/Create
        public ActionResult SelectDish(int id)
        {
            DishSelectView.Ingredients.Clear();
            Dish dish = db.Dishes.Get(id);

            DishSelectView.Name = dish.Name;
            DishSelectView.DishesAmount = 1;
            foreach (Recipe _recipe in dish.Recipes)
            {
                foreach (var prod in db.Products.GetList(1)) //1 - значит продукты которые являются компонентами для пиццы
                {
                    Ingredient customIngredient = new Ingredient() { ProductId = prod.Id, quantity = 0, productName = prod.Name };
                    bool addP = false;
                    //в выбранное блюдо с рецепта переписываем компоненты
                    foreach (Ingredient ingredient in _recipe.Ingredients)
                    {
                        if (ingredient.ProductId == customIngredient.ProductId)
                        {
                            customIngredient.quantity = ingredient.quantity;
                            
                            DishSelectView.Ingredients.Add(customIngredient);
                            addP = true;
                        }
                    }
                    if (!addP)
                        //добавляем продукты (не по рецепту) которые могут использоваться в пицце 
                        DishSelectView.Ingredients.Add(customIngredient);
                }
            }
            DishSelectView.price = GetPrice();
            if (dish.Recipes.Count() == 1)
                DishSelectView.ComboBox = false;
            else
                DishSelectView.ComboBox = true;

            return View(DishSelectView);
        }

        [HttpPost]
        public ActionResult SelectDish(DishSelect ds)
        {

            db.DishSelects.Create(DishSelectView);
            db.Save();
            return RedirectToAction("Create", "Orders");

        }
        public ActionResult DeleteFilling(int id)
        {
            foreach (Ingredient _ingredient in DishSelectView.Ingredients)
            {
                if (_ingredient.ProductId == id)
                    _ingredient.quantity = 0;
            }
            DishSelectView.price = GetPrice();
            return View("SelectDish",DishSelectView);
        }

        public ActionResult AddFilling(int id)
        {
            foreach(Ingredient _ingredient in DishSelectView.Ingredients)
            {
                float step = (float)0.1;
                if (db.Products.Get(id).IsInteger)
                    step = 1;
                if (_ingredient.ProductId == id)                    
                        _ingredient.quantity = _ingredient.quantity + step;                    
            }           
            DishSelectView.price = GetPrice();
            return View("SelectDish", DishSelectView);
        }
        public ActionResult AddDishCount()
        {
            DishSelectView.DishesAmount++;
            DishSelectView.price = GetPrice();
            return View("SelectDish",DishSelectView);
        }        
        public ActionResult SubDishCount()
        {
            if (DishSelectView.DishesAmount > 1)
            {
                DishSelectView.DishesAmount--;
                DishSelectView.price = GetPrice();
            }
            
            return View("SelectDish", DishSelectView);
        }

        public float GetPrice()
        {
            float price = 0;
            
           foreach(var _ingredient in DishSelectView.Ingredients)
                if (_ingredient.quantity>0)
                {
                    price += _ingredient.quantity * db.Products.Get(_ingredient.ProductId.Value).SellPrice;
                }
                return (price*DishSelectView.DishesAmount);
        }
    }
}

Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestTaskPizza.Models;
using TestTaskPizza.Models.Repositories;

namespace TestTaskPizza.Controllers
{
    public class DishesController : Controller
    {
        UoW db;
        static Dish _dish = new Dish(); 
        public DishesController()
        {
            db = new UoW();
            
            if (db.Groups.Count() == 0)
            {
                db.Groups.Create(new Group { GroupName = "Блюдо", SubName = "Пицца", FullName = "Блюдо: Пицца" });
                db.Groups.Create(new Group { GroupName = "Блюдо", SubName = "Соусы", FullName = "Блюдо: Соусы" });
                db.Groups.Create(new Group { GroupName = "Блюдо", SubName = "Салаты", FullName = "Блюдо: Салаты" }); ;
                db.Groups.Create(new Group { GroupName = "Блюдо", SubName = "Горячие блюда", FullName = "Блюдо: Горячие блюда" });
                db.Groups.Create(new Group { GroupName = "Напитки", SubName = "Вода газированная и негазированная", FullName = "Напитки: Вода газированная и негазированная" });
                db.Groups.Create(new Group { GroupName = "Напитки", SubName = "Соки", FullName = "Напитки: Соки" });
                db.Groups.Create(new Group { GroupName = "Готовая продукция", SubName = "Чипсы", FullName = "Готовая продукция: Чипсы" });
                db.Groups.Create(new Group { GroupName = "Готовая продукция", SubName = "Сухарики", FullName = "Готовая продукция: Сухарики" });

                db.Save();
            }
        }
        // GET: Dishes
        public ActionResult Index(int? Group)
        {            
            SelectList allGroups = new SelectList(db.Groups.GetList(), "Id", "FullName");
            ViewData["Groups"] = allGroups;
            
            return View(db.Dishes.GetList(Group));
        }

        // GET: Dishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Dish dish = db.Dishes.Get((int)id);            
            if (dish == null)
            {
                return HttpNotFound();
            }

            string receptsName = "";
            foreach (var rec in dish.Recipes)
            {
                receptsName += rec.RecipeName + "; ";
            }
            if (dish.Recipes.Count() == 1)
                ViewBag.receptsName = "В состав блюда входит рецепт - " + receptsName;                   
            else
                ViewBag.receptsName = "В состав Комбо-набора входят рецепты: " + receptsName;
            
            //ViewBag.receptsName = receptsName;
            return View(dish);
        }

        // GET: Dishes/Create
        public ActionResult Create()
        {
            SelectList allrecipes = new SelectList (db.Recipes.GetList(), "Id", "RecipeName");            
            SelectList allGroups = new SelectList(db.Groups.GetList(), "Id", "FullName");

            ViewBag.Recipes = allrecipes;
            ViewBag.Groups = allGroups;
            
            if (_dish.Recipes.Count() == 0)
                _dish.Recipes.Add(new Recipe());

            return View(_dish);
        }

        public ActionResult AddRecipe()
        {
            _dish.Recipes.Add(new Recipe());
            return RedirectToAction("Create");
        }
        public ActionResult DeleteRecipe()
        {
            _dish.Recipes.Remove(_dish.Recipes.FirstOrDefault());
            return RedirectToAction("Create");
        }

        // POST: Dishes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,GroupId")] Dish dish, HttpPostedFileBase file, List<int> Rec)
        {
            foreach (var recID in Rec) //если блюдо состоит из нескольких рецептов (комбо набор)
            {
                Recipe reciep = db.Recipes.Get(recID);
                dish.Recipes.Add(reciep);
            }

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string g1 = System.Web.Hosting.HostingEnvironment.MapPath("~/") + "Content\\Images\\" + file.FileName;                    
                    file.SaveAs(g1);
                    dish.ImagePath = file.FileName;
                }
                db.Dishes.Create(dish);
                db.Save();
                return RedirectToAction("Index");
            }

            return View(dish);
        }

        // GET: Dishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Get(id.Value);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Group")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                db.Dishes.Update(dish);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Get(id.Value);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Dishes.Delete(id);
            db.Save();
            return RedirectToAction("Index");
        }
    }
}

Views/Dishes/Create.cshtml
@model TestTaskPizza.Models.Dish

@{
    ViewBag.Title = "Создаём блюдо!";
}

<h3>Создание блюда по рецепту (или по рецептам)</h3>

@using (Html.BeginForm("Create", "Dishes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Group, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GroupId, ViewBag.Groups as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>
        @foreach (var receptID in Model.Recipes)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Recipes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Rec", ViewBag.Recipes as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Recipes, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        @Html.ActionLink("Добавить рецепт (для комбо наборов)", "AddRecipe", "Dishes", null, null)
        <br />
        @Html.ActionLink("Убрать рецепт", "DeleteRecipe", "Dishes", null, null)

        <div class="form-group">
            <fieldset>
                @Html.LabelFor(model => model.ImagePath)

                <input type="file" name="file" />
            </fieldset>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Создать" class="btn btn-primary" />
                </div>
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

Views/Dishes/Delete.cshtml
@model TestTaskPizza.Models.Dish

@{
    ViewBag.Title = "Удаление";
}

<h3>Вы уверены что хотите удалить это блюдо?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Dishes/Details.cshtml
@model TestTaskPizza.Models.Dish

@{
    ViewBag.Title = "Подробности";
}

<div>
    <h3>Блюдо</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Recipes)
        </dt>
        <dd>
            @ViewBag.receptsName
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Dishes/Index.cshtml
@model IEnumerable<TestTaskPizza.Models.Dish>

@{
    ViewBag.Title = "Блюда";
}


<div class="container">
    <div class="row">
        <div class="col">
            @using (Html.BeginForm("Index", "Dishes", FormMethod.Post))
            {
                <div class="container-fluid">
                    @Html.DropDownList("Group", (SelectList)ViewData["Groups"], new { @class = "form-control" })
                    <input type="submit" value="Показать" class="btn btn-primary" />
                </div>
            }            
        </div>
        <div class="col-md-auto">
            <h3>@Html.ActionLink("Добавить новое блюдо", "Create")</h3>
        </div>
        <div class="col">
            <h3>@Html.ActionLink("Показать все", "Index", "Dishes", null, null)</h3>
        </div>
    </div>
</div>
<div class="card-group">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-6">
                <div class="card text-center" style="width: 18rem;">
                    @{
                        if (item.ImagePath != null)
                        {
                            <img src="~/Content/Images/@Url.Content(item.ImagePath)" class="card-img-top" alt="...">
                        }
                    }
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">Цена: @item.price.ToString("N2")</p>
                        @Html.ActionLink("Выбрать", "SelectDish", "DishSelect", new { id = item.Id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Детали", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id })

                    </div>
                </div>
            </div>
        }
    </div>
</div>

